const bcrypt = require("bcrypt");
const data = {
  users: [
    {
      name: "Admin",
      email: "admin@example.com",
      // password: bcrypt.hash("123456", 12),
      password: "$2b$12$43Fvr7FTIh30x7naBikq3u/ZOh9Cz43sweuEQcJoMjNThjNbfb0Wi",
      isAdmin: true,
    },
    {
      name: "Seller",
      email: "seller@example.com",
      // password: bcrypt.hash("123456", 12),
      password: "$2b$12$43Fvr7FTIh30x7naBikq3u/ZOh9Cz43sweuEQcJoMjNThjNbfb0Wi",
      isSeller: true,
      seller: {
        name: "Cuong",
        logo: "/assets/images/productImage/p1.jpg",
        description: "best seller",
        rating: 4,
        numReviews: 120,
      },
    },
    {
      name: "User1",
      email: "user@example.com",
      // password: bcrypt.hash("123456", 12),
      password: "$2b$12$43Fvr7FTIh30x7naBikq3u/ZOh9Cz43sweuEQcJoMjNThjNbfb0Wi",
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Loa Bluetooth JBL Charge 4",
      category: "Loa",
      image1: "/assets/images/productImage/L1.jpg",
      image2: "/assets/images/productImage/L2.jpg",
      image3: "/assets/images/productImage/L3.jpg",
      price: 120,
      countInStock: 10,
      brand: "JBL",
      rating: 4,
      numReviews: 10,
      description: "WIRELESS BLUETOOTH STREAMING: Wirelessly connect up to 2 smartphones or tablets to the speaker and take turns enjoying powerful sound.",
    },
    {
      name: "Loa Bluetooth Sony SRS-XE200",
      category: "Loa",
      image1: "/assets/images/productImage/k4.jpg",
      image2: "/assets/images/productImage/k2.jpg",
      image3: "/assets/images/productImage/k3.jpg",
      price: 100,
      countInStock: 20,
      brand: "Sony",
      rating: 4,
      numReviews: 10,
      description: "The XE200 speaker shares the same sound experience with everyone in your venue. Plus, it's lightweight and has a handy strap, meaning that you can take your music wherever you go.",
    },
    {
      name: "Máy ảnh kỹ thuật số Sony ZV-E10L",
      category: "camera",
      image1: "/assets/images/productImage/m4.jpg",
      image2: "/assets/images/productImage/m2.jpg",
      image3: "/assets/images/productImage/m3.jpg",
      price: 2200,
      countInStock: 0,
      brand: "Sony",
      rating: 5,
      numReviews: 17,
      description: "With the new version software, Real-time Eye AF for animal is available when shooting movie. By setting the camera's subject detection type to Animal in advance, you can automatically detect and track an animal's eyes, for greater success in both photos and movies of your pets at home",
    },
    {
      name: "Máy ảnh Canon EOS M50 Mark II ( Black )",
      category: "camera",
      image1: "/assets/images/productImage/ca1.jpg",
      image2: "/assets/images/productImage/ca2.jpg",
      image3: "/assets/images/productImage/ca3.jpg",
      price: 7800,
      countInStock: 15,
      brand: "Canon",
      rating: 5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Máy ảnh Nikon Z6 II",
      category: "camera",
      image1: "/assets/images/productImage/ca4.jpg",
      image2: "/assets/images/productImage/ca5.jpg",
      image3: "/assets/images/productImage/ca6.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 3,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Apple Watch SE 2022 40mm",
      category: "Watch",
      image1: "/assets/images/productImage/w1.jpg",
      image2: "/assets/images/productImage/w2.jpg",
      image3: "/assets/images/productImage/w3.jpg",
      price: 1390,
      countInStock: 12,
      brand: "Apple",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Apple Watch SE 2021 40mm",
      category: "Watch",
      image1: "/assets/images/productImage/w2.jpg",
      image2: "/assets/images/productImage/w1.jpg",
      image3: "/assets/images/productImage/w3.jpg",
      price: 1390,
      countInStock: 12,
      brand: "Apple",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Apple Watch SE 2020 40mm",
      category: "Watch",
      image1: "/assets/images/productImage/w3.jpg",
      image2: "/assets/images/productImage/w2.jpg",
      image3: "/assets/images/productImage/w1.jpg",
      price: 1390,
      countInStock: 12,
      brand: "Apple",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Kieslect Kr Pro 2022",
      category: "Watch",
      image1: "/assets/images/productImage/d3.jpg",
      image2: "/assets/images/productImage/d2.jpg",
      image3: "/assets/images/productImage/d1.jpg",
      price: 2390,
      countInStock: 12,
      brand: "Kieslect",
      rating: 4.5,
      numReviews: 15,
      description: "Kieslect calling watch Kr Pro boasting a powerful 2-in-1 calling chip & stable 5.2 bluetooth.Kr Pro smartwatch with 70 sports modes.",
    },
    {
      name: "Kieslect Kr Vip Pro 2022",
      category: "Watch",
      image1: "/assets/images/productImage/d1.jpg",
      image2: "/assets/images/productImage/d2.jpg",
      image3: "/assets/images/productImage/d3.jpg",
      price: 2390,
      countInStock: 12,
      brand: "Kieslect",
      rating: 4.5,
      numReviews: 15,
      description: "Kieslect calling watch Kr Pro boasting a powerful 2-in-1 calling chip & stable 5.2 bluetooth.Kr Pro smartwatch with 70 sports modes.",
    },
    {
      name: "Kieslect Kr Max Vip Pro 2022",
      category: "Watch",
      image1: "/assets/images/productImage/d2.jpg",
      image2: "/assets/images/productImage/d1.jpg",
      image3: "/assets/images/productImage/d3.jpg",
      price: 2490,
      countInStock: 12,
      brand: "Kieslect",
      rating: 4.5,
      numReviews: 15,
      description: "Kieslect calling watch Kr Pro boasting a powerful 2-in-1 calling chip & stable 5.2 bluetooth.Kr Pro smartwatch with 70 sports modes.",
    },
    {
      name: " Gimbal Zhiyun Q3 Vip Pro 2022",
      category: "Gimbal",
      image1: "/assets/images/productImage/g2.jpg",
      image2: "/assets/images/productImage/g1.jpg",
      image3: "/assets/images/productImage/g3.jpg",
      price: 2490,
      countInStock: 12,
      brand: "Zhiyun",
      rating: 4.5,
      numReviews: 15,
      description: "Kieslect calling watch Kr Pro boasting a powerful 2-in-1 calling chip & stable 5.2 bluetooth.Kr Pro smartwatch with 70 sports modes.",
    },
    {
      name: "Máy ảnh Nikon filip Z7 I",
      category: "camera",
      image1: "/assets/images/productImage/ca5.jpg",
      image2: "/assets/images/productImage/ca4.jpg",
      image3: "/assets/images/productImage/ca6.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 3,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Máy ảnh Nikon k6 II",
      category: "camera",
      image1: "/assets/images/productImage/ca6.jpg",
      image2: "/assets/images/productImage/ca5.jpg",
      image3: "/assets/images/productImage/ca4.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 3,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Loa Bluetooth Sony SRS-XE200",
      category: "Loa",
      image1: "/assets/images/productImage/k3.jpg",
      image2: "/assets/images/productImage/k2.jpg",
      image3: "/assets/images/productImage/k3.jpg",
      price: 100,
      countInStock: 20,
      brand: "Sony",
      rating: 4,
      numReviews: 10,
      description: "The XE200 speaker shares the same sound experience with everyone in your venue. Plus, it's lightweight and has a handy strap, meaning that you can take your music wherever you go.",

    },
    {
      name: "Loa Bluetooth Sony Z2 SRS-XE200",
      category: "Loa",
      image1: "/assets/images/productImage/k1.jpg",
      image2: "/assets/images/productImage/k2.jpg",
      image3: "/assets/images/productImage/k3.jpg",
      price: 100,
      countInStock: 20,
      brand: "Sony",
      rating: 4,
      numReviews: 10,
      description: "The XE200 speaker shares the same sound experience with everyone in your venue. Plus, it's lightweight and has a handy strap, meaning that you can take your music wherever you go.",

    },
  ],
};
module.exports = {
  data,
};
